CREATE TABLE stg.Receitas_publicas(
	 CODIGO_ORGAO_SUPERIOR VARCHAR(10)
	,NOME_ORGAO_SUPERIOR VARCHAR(50)
	,CODIGO_ORGAO VARCHAR(10)
	,NOME_ORGAO VARCHAR(100)
	,CODIGO_UNIDADE_GESTORA VARCHAR(20)
	,NOME_UNIDADE_GESTORA VARCHAR(100)
	,CATEGORIA_ECONOMICA VARCHAR(50)
	,ORIGEM_RECEITA VARCHAR(50)
	,ESPECIE_RECEITA VARCHAR(100)
	,DETALHAMENTO VARCHAR(100)
	,VALOR_PREVISTO_ATUALIZADO VARCHAR(50)
	,VALOR_LANCADO FLOAT(50)
	,VALOR_REALIZADO FLOAT(50)
	,PERCENTUAL_REALIZADO VARCHAR(50)
	,DATA_LANCAMENTO DATETIME
	,ANO_EXERCICIO DATETIME
	,ORIGEM VARCHAR(50)
)

