USE [BI_Staging]
GO
/****** Object:  StoredProcedure [stg].[stpOM_SYM_COMPANY]    Script Date: 12/07/2022 21:43:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


ALTER PROCEDURE [stg].[stpReceitas_publicas]
AS BEGIN

-- DELETO A MINHA TABELA TEMPORARIA
	IF(OBJECT_ID('BI_Staging.stg.temp_Receitas_publicas') IS NOT NULL) 
		DROP TABLE BI_Staging.stg.temp_Receitas_publicas

-- AQUI ELE PEGA OS DADOS DA BASE DE DADOS EM PRODUÇÃO E COLOCA-OS EM UMA TABELA TEMPORÁRIA
SELECT * INTO BI_Staging.stg.temp_Receitas_publicas 
FROM(
	SELECT 
		 CÓDIGO_ÓRGÃO_SUPERIOR
		,NOME_ÓRGÃO_SUPERIOR
		,CÓDIGO_ÓRGÃO
		,NOME_ÓRGÃO
		,CÓDIGO_UNIDADE_GESTORA
		,NOME_UNIDADE_GESTORA
		,CATEGORIA_ECONÔMICA
		,ORIGEM_RECEITA
		,ESPÉCIE_RECEITA
		,DETALHAMENTO
		,VALOR_PREVISTO_ATUALIZADO
		,VALOR_LANÇADO
		,VALOR_REALIZADO
		,PERCENTUAL_REALIZADO
		,DATA_LANÇAMENTO
		,ANO_EXERCÍCIO
		,'RECEITA_PUBLICA' AS ORIGEM
	FROM [PROD].[dbo].[2020_Receitas]
	UNION ALL
	SELECT 
		 CÓDIGO_ÓRGÃO_SUPERIOR
		,NOME_ÓRGÃO_SUPERIOR
		,CÓDIGO_ÓRGÃO
		,NOME_ÓRGÃO
		,CÓDIGO_UNIDADE_GESTORA
		,NOME_UNIDADE_GESTORA
		,CATEGORIA_ECONÔMICA
		,ORIGEM_RECEITA
		,ESPÉCIE_RECEITA
		,DETALHAMENTO
		,VALOR_PREVISTO_ATUALIZADO
		,VALOR_LANÇADO
		,VALOR_REALIZADO
		,PERCENTUAL_REALIZADO
		,DATA_LANÇAMENTO
		,ANO_EXERCÍCIO
		,'RECEITA_PUBLICA' AS ORIGEM
	FROM [PROD].[dbo].[2021_Receitas]
	UNION ALL
	SELECT 
	CÓDIGO_ÓRGÃO_SUPERIOR
		,NOME_ÓRGÃO_SUPERIOR
		,CÓDIGO_ÓRGÃO
		,NOME_ÓRGÃO
		,CÓDIGO_UNIDADE_GESTORA
		,NOME_UNIDADE_GESTORA
		,CATEGORIA_ECONÔMICA
		,ORIGEM_RECEITA
		,ESPÉCIE_RECEITA
		,DETALHAMENTO
		,VALOR_PREVISTO_ATUALIZADO
		,VALOR_LANÇADO
		,VALOR_REALIZADO
		,PERCENTUAL_REALIZADO
		,DATA_LANÇAMENTO
		,ANO_EXERCÍCIO
		,'RECEITA_PUBLICA' AS ORIGEM
	FROM [PROD].[dbo].[2022_Receitas]
	) A


-- GARANTE QUE A TABELA DESTINO NO BI_STAGING ESTEJA LIMPA
TRUNCATE TABLE [stg].[Receitas_publicas]

-- GARANTINDO QUE ESTÁ LIMPO, INSERIMOS TODOS OS DADOS NOVAMENTE, A PARTIR DA TABELA TEMPORARIA
INSERT INTO [stg].[Receitas_publicas]
SELECT * FROM BI_Staging.stg.temp_Receitas_publicas 

-- DELETO A MINHA TABELA TEMPORARIA
	IF(OBJECT_ID('BI_Staging.stg.temp_Receitas_publicas ') IS NOT NULL) 
		DROP TABLE BI_Staging.stg.temp_Receitas_publicas 

END;
